[programs.devnet]
mysolanaproject = "4oZ1rixYH1xn7vZNNtuKDUTRsoGPLiukfVL2XhmAMaCF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/murzahell/.config/solana/id.json"

[scripts]
test = "node tests/mysolanaproject.js" 
